# Generated by Django 4.0 on 2023-09-19 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_entrenamiento', models.CharField(default='', max_length=200)),
                ('fecha', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='projects.user')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.CharField(blank=True, max_length=20, null=True)),
                ('altura', models.CharField(blank=True, max_length=20, null=True)),
                ('edad', models.CharField(blank=True, max_length=20, null=True)),
                ('objetivo', models.CharField(blank=True, max_length=250, null=True)),
                ('genero', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='projects.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('repeticiones', models.CharField(max_length=200)),
                ('peso', models.CharField(max_length=200)),
                ('descanso', models.CharField(blank=True, max_length=20, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=3000, null=True)),
                ('entrenamiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios', to='projects.entrenamiento')),
            ],
        ),
    ]
