# Generated by Django 4.2.2 on 2023-09-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_plan_personaldata_ejercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='tipo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
