# Generated by Django 4.2.2 on 2023-09-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_entrenamiento_tipo_alter_entrenamiento_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='hora_fin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='hora_inicio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
