# Generated by Django 4.2.2 on 2023-09-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_plan_hora_fin_plan_hora_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='hora_fin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='hora_inicio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
