# Generated by Django 4.2.2 on 2023-09-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_plan_hora_fin_alter_plan_hora_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='equipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='one_rm',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
