# Generated by Django 4.2.2 on 2023-09-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_ejercicio_equipo_ejercicio_one_rm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
