# Generated by Django 4.2.2 on 2023-10-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_comida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comida',
            old_name='descripcion',
            new_name='cena',
        ),
        migrations.RemoveField(
            model_name='comida',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='comida',
            name='turno',
        ),
        migrations.AddField(
            model_name='comida',
            name='comida',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comida',
            name='desayuno',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='comida',
            name='merienda',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
