# Generated by Django 4.2.2 on 2023-10-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_rename_descripcion_comida_cena_remove_comida_titulo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comida',
            old_name='nutrientes',
            new_name='notas',
        ),
    ]
