# Generated by Django 4.2.2 on 2023-10-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_rename_nutrientes_comida_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='comida',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
